apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: devops
  labels:
    app: postgres
data:
  POSTGRES_DB: "devops"
  POSTGRES_USER: "postgres"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  # Performance tuning for 32GB RAM system
  POSTGRES_SHARED_BUFFERS: "2GB"
  POSTGRES_EFFECTIVE_CACHE_SIZE: "6GB"
  POSTGRES_MAINTENANCE_WORK_MEM: "512MB"
  POSTGRES_CHECKPOINT_COMPLETION_TARGET: "0.9"
  POSTGRES_WAL_BUFFERS: "16MB"
  POSTGRES_DEFAULT_STATISTICS_TARGET: "100"
  POSTGRES_RANDOM_PAGE_COST: "1.1"
  POSTGRES_EFFECTIVE_IO_CONCURRENCY: "200"
  POSTGRES_WORK_MEM: "32MB"
  POSTGRES_MIN_WAL_SIZE: "1GB"
  POSTGRES_MAX_WAL_SIZE: "4GB"
  POSTGRES_MAX_WORKER_PROCESSES: "12"
  POSTGRES_MAX_PARALLEL_WORKERS_PER_GATHER: "4"
  POSTGRES_MAX_PARALLEL_WORKERS: "12"
  POSTGRES_MAX_PARALLEL_MAINTENANCE_WORKERS: "4"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
  namespace: devops
  labels:
    app: postgres
data:
  init.sql: |
    -- Create databases for microservices
    CREATE DATABASE user_service;
    CREATE DATABASE order_service;
    CREATE DATABASE notification_service;
    CREATE DATABASE gitlab;
    
    -- Create users for each service
    CREATE USER user_service_user WITH ENCRYPTED PASSWORD 'user_service_pass';
    CREATE USER order_service_user WITH ENCRYPTED PASSWORD 'order_service_pass';
    CREATE USER notification_service_user WITH ENCRYPTED PASSWORD 'notification_service_pass';
    CREATE USER gitlab_user WITH ENCRYPTED PASSWORD 'gitlab_pass';
    
    -- Grant privileges
    GRANT ALL PRIVILEGES ON DATABASE user_service TO user_service_user;
    GRANT ALL PRIVILEGES ON DATABASE order_service TO order_service_user;
    GRANT ALL PRIVILEGES ON DATABASE notification_service TO notification_service_user;
    GRANT ALL PRIVILEGES ON DATABASE gitlab TO gitlab_user;
    
    -- Create schemas
    \c user_service;
    CREATE SCHEMA IF NOT EXISTS user_service AUTHORIZATION user_service_user;
    
    \c order_service;
    CREATE SCHEMA IF NOT EXISTS order_service AUTHORIZATION order_service_user;
    
    \c notification_service;
    CREATE SCHEMA IF NOT EXISTS notification_service AUTHORIZATION notification_service_user;