apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: devops
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  ports:
  - name: nexus-ui
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: docker-group
    port: 8082
    targetPort: 8082
    protocol: TCP
  - name: docker-hosted
    port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP