apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: default
data:
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USERNAME: "microservices_user"
  
  # Individual Database Names
  USER_DB_NAME: "user_service_db"
  ORDER_DB_NAME: "order_service_db"
  NOTIFICATION_DB_NAME: "notification_service_db"
  INVENTORY_DB_NAME: "inventory_service_db"
  AUDIT_DB_NAME: "audit_service_db"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Kafka Configuration
  KAFKA_BROKERS: "kafka-service:9092"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  
  # JWT Configuration
  JWT_EXPIRATION: "86400000"
  JWT_REFRESH_EXPIRATION: "604800000"
  
  # Application Configuration
  APP_NAME: "Microservices Platform"
  APP_VERSION: "1.0.0"
  APP_ENVIRONMENT: "kubernetes"
  DEBUG_MODE: "true"
  LOG_LEVEL: "INFO"
  ENABLE_SWAGGER: "true"
  ENABLE_ACTUATOR: "true"
  ENABLE_METRICS: "true"
  
  # Service Ports
  SERVER_PORT_USER: "8081"
  SERVER_PORT_ORDER: "8082"
  SERVER_PORT_NOTIFICATION: "8083"
  SERVER_PORT_INVENTORY: "8084"
  SERVER_PORT_AUDIT: "8085"
  
  # Spring Configuration
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  
  # Management/Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"