apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config-secure
  namespace: microservices
  labels:
    app: microservices
    config.type: non-sensitive
data:
  # Non-sensitive Database Configuration
  DB_HOST: "postgres.devops.svc.cluster.local"
  DB_PORT: "5432"
  DB_DRIVER: "org.postgresql.Driver"
  
  # Non-sensitive Redis Configuration 
  REDIS_HOST: "redis.devops.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_TIMEOUT: "2000ms"
  
  # Non-sensitive Kafka Configuration
  KAFKA_HOST: "kafka.devops.svc.cluster.local"
  KAFKA_PORT: "9092"
  
  # JWT Configuration (non-sensitive values only)
  JWT_EXPIRATION: "86400000"
  JWT_REFRESH_EXPIRATION: "604800000"
  JWT_ALGORITHM: "HS256"
  
  # Application Configuration
  APP_NAME: "Microservices Platform"
  APP_VERSION: "1.0.0"
  APP_ENVIRONMENT: "kubernetes"
  LOG_LEVEL: "INFO"
  ENABLE_SWAGGER: "false"  # Security: disable in production
  ENABLE_ACTUATOR: "true"
  ENABLE_METRICS: "true"
  
  # Spring Configuration
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"  # Security: prevent auto-schema changes
  SPRING_JPA_SHOW_SQL: "false"  # Security: prevent SQL logging
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  
  # Database Connection Pool (non-sensitive)
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "10"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "5"
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "20000"
  SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: "600000"
  SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: "1800000"
  
  # Security Configuration (non-sensitive)
  SECURITY_REQUIRE_SSL: "true"
  SECURITY_SESSION_TIMEOUT: "1800"  # 30 minutes
  SECURITY_MAX_LOGIN_ATTEMPTS: "5"
  SECURITY_LOCKOUT_DURATION: "900"  # 15 minutes
  
  # Rate Limiting Configuration
  RATE_LIMIT_REQUESTS_PER_MINUTE: "5"
  RATE_LIMIT_WINDOW_SECONDS: "60"
  
  # Management/Actuator (security-conscious)
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when-authorized"  # Security: limit details
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_SECURITY_ENABLED: "true"
  
  # Logging Configuration
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "WARN"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "INFO"
  LOGGING_LEVEL_COM_MICROSERVICES: "INFO"
  
  # CORS Configuration (security)
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,https://localhost:3000"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_MAX_AGE: "3600"
  
  # Health Check Configuration
  HEALTH_CHECK_INTERVAL: "30"
  HEALTH_CHECK_TIMEOUT: "5"
  HEALTH_CHECK_RETRIES: "3"