apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
  labels:
    app: microservices
data:
  # Database Configuration
  DB_HOST: "postgres.devops.svc.cluster.local"
  DB_PORT: "5432"
  
  # Redis Configuration 
  REDIS_HOST: "redis.devops.svc.cluster.local"
  REDIS_PORT: "6379"
  
  # Kafka Configuration
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka.devops.svc.cluster.local:9092"
  
  # JWT Configuration
  JWT_EXPIRATION: "86400000"
  JWT_REFRESH_EXPIRATION: "604800000"
  
  # Application Configuration
  APP_NAME: "Microservices Platform"
  APP_VERSION: "1.0.0"
  APP_ENVIRONMENT: "kubernetes"
  DEBUG_MODE: "true"
  LOG_LEVEL: "INFO"
  ENABLE_SWAGGER: "true"
  ENABLE_ACTUATOR: "true"
  ENABLE_METRICS: "true"
  
  # Spring Configuration
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  
  # Management/Actuator
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"